services:
  march7thassistant:
    container_name: m7a
    build: .
    # image: ghcr.io/moesnow/march7thassistant:latest
    # image: ghcr.nju.edu.cn/moesnow/march7thassistant:latest
    volumes:
      - ./config.yaml:/m7a/config.yaml
      - ./logs:/m7a/logs
      - ./3rdparty/WebBrowser/UserProfile:/m7a/3rdparty/WebBrowser/UserProfile
    environment:
      - MARCH7TH_LOG_LEVEL=DEBUG
    network_mode: "bridge"
    shm_size: 1g
    restart: unless-stopped
