name: Build realtime release

# 触发条件：手动触发或推送触发
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      PYTHONHASHSEED: 0
      SOURCE_DATE_EPOCH: 315532800
      MARCH7TH_LOG_LEVEL: DEBUG
      MARCH7TH_BROWSER_DOWNLOAD_USE_MIRROR: false

    steps:
      # 签出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "false"
          fetch-depth: 0

      # 检查版本文件是否被修改
      - name: Check if version.txt was changed
        id: check_version
        run: |
          $changedFiles = git diff HEAD~1 HEAD --name-only
          if ($changedFiles -match 'assets[/\\]config[/\\]version\.txt') {
            Write-Host "version.txt was changed in the latest commit, skipping the build"
            echo "should_build=false" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "version.txt was not changed, proceeding with the build"
            echo "should_build=true" >> $env:GITHUB_OUTPUT
          }

      # 设置Python环境
      - name: Set up python
        if: steps.check_version.outputs.should_build == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.11"
          cache: "pip"

      # 安装依赖
      - name: Install dependencies
        if: steps.check_version.outputs.should_build == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller==6.17.0
          python build.py --task ocr

      # 生成程序
      - name: Generate program
        if: steps.check_version.outputs.should_build == 'true'
        run: |
          pyinstaller -D --distpath .\dist\ -i .\assets\logo\Terminal.ico --contents-directory libraries --collect-all rapidocr --exclude-module PyQt5 --uac-admin -n "March7th Assistant" main.py -y
          pyinstaller -D --distpath .\dist\ -i .\assets\logo\March7th.ico --contents-directory libraries --collect-all rapidocr --uac-admin -n "March7th Launcher" app.py -y
          pyinstaller -F --distpath .\dist\March7thAssistant\ -i .\assets\logo\Updater.ico -n "March7th Updater" --exclude-module numpy --exclude-module pandas --uac-admin updater.py -y

      # 移动资源到dist目录
      - name: Move assets to dist directory
        if: steps.check_version.outputs.should_build == 'true'
        run: |
          Copy-Item -Path ".\dist\March7th Assistant\*" -Destination ".\dist\March7thAssistant\" -Recurse -Force
          Copy-Item -Path ".\dist\March7th Launcher\*" -Destination ".\dist\March7thAssistant\" -Recurse -Force
          Copy-Item -Path ".\assets\" -Destination ".\dist\March7thAssistant\assets\" -Recurse -Force
          Copy-Item -Path ".\README.md" -Destination ".\dist\March7thAssistant\" -Force

      # 创建压缩包
      - name: Create archive
        if: steps.check_version.outputs.should_build == 'true'
        run: |
          Rename-Item -Path .\dist\March7thAssistant -NewName March7thAssistant_${{ github.run_number }}
          .\assets\binary\7za.exe a -t7z .\dist\March7thAssistant_${{ github.run_number }}.7z .\dist\March7thAssistant_${{ github.run_number }}\

      # 上传压缩包
      - name: Upload artifact
        if: steps.check_version.outputs.should_build == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: March7thAssistant_${{ github.run_number }}.7z
          path: ./dist/March7thAssistant_${{ github.run_number }}.7z
          compression-level: 0 # no compression
